class ResponseCode {

  //提供快速取得錯誤碼敘述文
  static String getLocalizedDisplayStr(String responseCode) {
    if (map.containsKey(responseCode)) {
      return map[responseCode]!;
    }
    return UNDEFINED_ERROR ;
  }

  static Map<String, String> map = {
    CODE_SUCCESS: SUCCESS,
    CODE_PARAMETER_FORMAT_ERROR: PARAMETER_FORMAT_ERROR,
    CODE_SYSTEM_MAINTENANCE: SYSTEM_MAINTENANCE,
    CODE_USER_ACCOUNT_SUSPENDED: USER_ACCOUNT_SUSPENDED,
    CODE_ACCOUNT_NOT_FOUND: ACCOUNT_NOT_FOUND,
    CODE_ALREADY_A_GROUP_MEMBER: ALREADY_A_GROUP_MEMBER,
    CODE_GROUP_MEMBERSHIP_EXCEEDS_LIMIT: GROUP_MEMBERSHIP_EXCEEDS_LIMIT,
    CODE_INCORRECT_USERNAME_OR_PASSWORD: INCORRECT_USERNAME_OR_PASSWORD,
    CODE_PASSWORD_VALIDATION_ERROR: PASSWORD_VALIDATION_ERROR,
    CODE_PLEASE_ENTER_SIX_TO_TWELVE_DIGIT_ALPHA_NUMERIC:
    PLEASE_ENTER_SIX_TO_TWELVE_DIGIT_ALPHA_NUMERIC,
    CODE_NOT_FULLY_EXITED_ROOM: NOT_FULLY_EXITED_ROOM,
    CODE_PLEASE_ENTER_10_DIGITS: PLEASE_ENTER_10_DIGITS,
    CODE_VERIFICATION_CODE_ERROR: VERIFICATION_CODE_ERROR,
    CODE_CLICK_DURATION_TOO_SHORT: CLICK_DURATION_TOO_SHORT,
    CODE_NICKNAME_CONTAINS_ILLEGAL_WORDS: NICKNAME_CONTAINS_ILLEGAL_WORDS,
    CODE_LENGTH_LIMIT_15_CHARACTERS: LENGTH_LIMIT_15_CHARACTERS,
    CODE_GROUP_NAME_ALREADY_EXISTS_1: GROUP_NAME_ALREADY_EXISTS_1,
    CODE_THIS_ACCOUNT_ALREADY_EXISTS: THIS_ACCOUNT_ALREADY_EXISTS,
    CODE_NICKNAME_CONTAINS_INAPPROPRIATE_WORDS:
    NICKNAME_CONTAINS_INAPPROPRIATE_WORDS,
    CODE_GROUP_NOT_FOUND: GROUP_NOT_FOUND,
    CODE_GROUP_NAME_ALREADY_EXISTS_2: GROUP_NAME_ALREADY_EXISTS_2,
    CODE_NICKNAME_ALREADY_EXISTS: NICKNAME_ALREADY_EXISTS,
    CODE_NOT_A_ROOM_USER: NOT_A_ROOM_USER,
    CODE_PLEASE_CHECK_AT_LEAST_ONE_PERMISSION:
    PLEASE_CHECK_AT_LEAST_ONE_PERMISSION,
    CODE_GROUP_CONTAINS_ACCOUNTS_CANNOT_DELETE:
    GROUP_CONTAINS_ACCOUNTS_CANNOT_DELETE,
    CODE_INSUFFICIENT_PERMISSIONS: INSUFFICIENT_PERMISSIONS,
    CODE_STATION_ERROR: STATION_ERROR,
    CODE_ALL_GROUP_MUTE: ALL_GROUP_MUTE,
    CODE_GROUP_MUTE: GROUP_MUTE,
    CODE_FRIEND_LIST_EXCEEDS_LIMIT: FRIEND_LIST_EXCEEDS_LIMIT,
    CODE_USERNAME_AND_NICKNAME_CANNOT_BE_THE_SAME:
    USERNAME_AND_NICKNAME_CANNOT_BE_THE_SAME,
    CODE_COIN_BALANCE_NOT_ENOUGH: COIN_BALANCE_NOT_ENOUGH,
    CODE_YOU_DONT_KNOW_YET: YOU_DONT_KNOW_YET,
    CODE_POINTS_NOT_ENOUGH: POINTS_NOT_ENOUGH,
    CODE_EXCEED_WITHDRAW_COUNT_LIMIT: EXCEED_WITHDRAW_COUNT_LIMIT,
    CODE_EXCEED_WITHDRAW_AMOUNT_LIMIT: EXCEED_WITHDRAW_AMOUNT_LIMIT,
    CODE_ILLEGAL_WITHDRAW_AMOUNT: ILLEGAL_WITHDRAW_AMOUNT,
    CODE_THIRDPARTY_FAILED: THIRDPARTY_FAILED,
    CODE_PARAMETER_MISSING: PARAMETER_MISSING,
    CODE_ONE_CLICK_LOGIN_ERROR: ONE_CLICK_LOGIN_ERROR,
    CODE_INVITATION_CODE_ERROR: INVITATION_CODE_ERROR,
    CODE_DUPLICATE_PHONE_NUMBER: DUPLICATE_PHONE_NUMBER,
    CODE_AVATAR_UNDER_REVIEW: AVATAR_UNDER_REVIEW,
    CODE_REAL_PERSON_VERIFICATION_UNDER_REVIEW: REAL_PERSON_VERIFICATION_UNDER_REVIEW,
    CODE_ALBUM_UNDER_REVIEW: ALBUM_UNDER_REVIEW,
    CODE_GREETING_UNDER_REVIEW: GREETING_UNDER_REVIEW,
    CODE_NICKNAME_UNDER_REVIEW: NICKNAME_UNDER_REVIEW,
    CODE_FILE_UPLOAD_EXCEEDS_LIMIT: FILE_UPLOAD_EXCEEDS_LIMIT,
    CODE_ACCOUNT_CANCELLATION_ERROR: ACCOUNT_CANCELLATION_ERROR,
    CODE_TID_ERROR_OR_EXPIRED: TID_ERROR_OR_EXPIRED,
    CODE_SMS_LOGIN_ERROR: SMS_LOGIN_ERROR,
    CODE_DUPLICATE_CALL_CHARGE: DUPLICATE_CALL_CHARGE,
    CODE_CALL_NOT_CHARGED: CALL_NOT_CHARGED,
    CODE_CALL_REQUEST_TIMEOUT: CALL_REQUEST_TIMEOUT,
    CODE_INVALID_GENDER: INVALID_GENDER,
    CODE_GREETING_TEMPLATE_LIMIT_EXCEEDED: GREETING_TEMPLATE_LIMIT_EXCEEDED,
    CODE_GREETING_TEMPLATE_IN_USE: GREETING_TEMPLATE_IN_USE,
    CODE_GREETING_TEMPLATE_UNDER_REVIEW: GREETING_TEMPLATE_UNDER_REVIEW,
    CODE_GREETING_TEMPLATE_UNAVAILABLE: GREETING_TEMPLATE_UNAVAILABLE,
    CODE_REAL_NAME_AUTH_FAILED: REAL_NAME_AUTH_FAILED,
    CODE_REAL_NAME_AUTH_TOO_FREQUENT_10: REAL_NAME_AUTH_TOO_FREQUENT_10,
    CODE_REAL_NAME_AUTH_TOO_FREQUENT_3: REAL_NAME_AUTH_TOO_FREQUENT_3,
    CODE_REAL_NAME_AUTH_FUNCTION_LOCK_10: REAL_NAME_AUTH_FUNCTION_LOCK_10,
    CODE_REAL_NAME_AUTH_FUNCTION_LOCK_3: REAL_NAME_AUTH_FUNCTION_LOCK_3,
    CODE_WITHDRAW_TOO_FREQUENT_30_MIN: WITHDRAW_TOO_FREQUENT_30_MIN,
    CODE_WITHDRAW_TOO_FREQUENT_1_MIN: WITHDRAW_TOO_FREQUENT_1_MIN,
    CODE_WITHDRAW_TOO_FREQUENT_5_MIN: WITHDRAW_TOO_FREQUENT_5_MIN,
    CODE_WITHDRAW_TOO_FREQUENT_1_HOUR: WITHDRAW_TOO_FREQUENT_1_HOUR,
    CODE_USER_NOT_AUTH_REAL_PERSON: USER_NOT_AUTH_REAL_PERSON,
    CODE_PUNCH_IN_AGAIN: PUNCH_IN_AGAIN,
    CODE_INVALID_IMAGE_FORMAT: INVALID_IMAGE_FORMAT,
    CODE_USER_LOGGED_IN_TWICE: USER_LOGGED_IN_TWICE,
    CODE_USER_NOT_LOGGED_IN: USER_NOT_LOGGED_IN,
    CODE_MEMBER_BUSY: MEMBER_BUSY,
    CODE_COHESION_IS_NOT_ENOUGH: COHESION_IS_NOT_ENOUGH,
    CODE_REAL_NAME_UNDER_REVIEW: REAL_NAME_UNDER_REVIEW,
    CODE_REGISTER_REQUEST_TIMEOUT: REGISTER_REQUEST_TIMEOUT,
    CODE_WITHDRAW_IS_DIFFERENT_WITH_BACKSTAGE: WITHDRAW_IS_DIFFERENT_WITH_BACKSTAGE,
    CODE_THIRD_PART_RESPONSE_ERROR: THIRD_PART_RESPONSE_ERROR,
    CODE_MEMBER_STATE_DELETE: MEMBER_STATE_DELETE,
    CODE_MEMBER_STATE_LOCK: MEMBER_STATE_LOCK,
    CODE_AVATAR_REVIEW_ERROR: AVATAR_REVIEW_ERROR,
    CODE_INTIMACY_POINTS_UP: INTIMACY_POINTS_UP,
    CODE_GENERATE_APPLE_ORDER_ERROR: GENERATE_APPLE_ORDER_ERROR,
    CODE_CAN_NOT_FOUND_DATA: CAN_NOT_FOUND_DATA,
    CODE_ALREADY_ADD_LIKE: ALREADY_ADD_LIKE,
    CODE_CALL_IS_BLACK_LISTED_ERROR:CALL_IS_BLACK_LISTED,
    CODE_REAL_NAME_AND_ID_CARD_IS_ALREADY_USED:REAL_NAME_AUTH_ALREADY_CERTIFIED,
    CODE_CONTENT_VIOLATES_REGULATIONS: CONTENT_VIOLATES_REGULATIONS,
    CODE_DATE_RANGE_NOT_EXCEED_62DAYS: DATE_RANGE_NOT_EXCEED_62DAYS,
    CODE_SEARCH_RANGE_NOT_EXCEED_31DAYS: SEARCH_RANGE_NOT_EXCEED_31DAYS,
    CODE_NUMBER_IS_AT_RISK: NUMBER_IS_AT_RISK,
    CODE_CALL_HAS_ENDED: CALL_HAS_ENDED,
    CODE_ACTIVITY_DONATE_GENDER_ERROR: ACTIVITY_DONATE_GENDER_ERROR,
    CODE_ACTIVITY_DONATE_NOT_ENOUGH_ERROR: ACTIVITY_DONATE_NOT_ENOUGH_ERROR,
  };

  static String UNDEFINED_ERROR = "未定义的错误";
  static String SUCCESS = "成功";
  static String PARAMETER_FORMAT_ERROR = "参数格式错误";
  static String SYSTEM_MAINTENANCE = "系统维护";
  static String USER_ACCOUNT_SUSPENDED = "用户账号已停用";
  static String ACCOUNT_NOT_FOUND = "查无账号";
  static String ALREADY_A_GROUP_MEMBER = "已为该群成员";
  static String GROUP_MEMBERSHIP_EXCEEDS_LIMIT = "群组人数超过上限";
  static String INCORRECT_USERNAME_OR_PASSWORD = "账号或密码错误";
  static String PASSWORD_VALIDATION_ERROR = "检核密码错误";
  static String PLEASE_ENTER_SIX_TO_TWELVE_DIGIT_ALPHA_NUMERIC = "请输入6-12位英数组合";
  static String NOT_FULLY_EXITED_ROOM = "尚未完全退出房间";
  static String PLEASE_ENTER_10_DIGITS = "请输入10位数字";
  static String VERIFICATION_CODE_ERROR = "验证码错误";
  static String CLICK_DURATION_TOO_SHORT = "点击时间过短";
  static String NICKNAME_CONTAINS_ILLEGAL_WORDS = "昵称含有不法字词";
  static String LENGTH_LIMIT_15_CHARACTERS = "长度上限15字元";
  static String GROUP_NAME_ALREADY_EXISTS_1 = "群组名称已存在";
  static String THIS_ACCOUNT_ALREADY_EXISTS = "该账号已存在";
  static String NICKNAME_CONTAINS_INAPPROPRIATE_WORDS = "昵称含有不当字词";
  static String GROUP_NOT_FOUND = "查无群组";
  static String GROUP_NAME_ALREADY_EXISTS_2 = "群组名称已存在";
  static String NICKNAME_ALREADY_EXISTS = "昵称已存在";
  static String NOT_A_ROOM_USER = "非本房用户";
  static String PLEASE_CHECK_AT_LEAST_ONE_PERMISSION = "请至少勾选1个权限";
  static String GROUP_CONTAINS_ACCOUNTS_CANNOT_DELETE = "组别存有账号，无法删除";
  static String INSUFFICIENT_PERMISSIONS = "暂无权限";
  static String STATION_ERROR = "站别错误";
  static String ALL_GROUP_MUTE = "全群禁言";
  static String GROUP_MUTE = "群禁言";
  static String FRIEND_LIST_EXCEEDS_LIMIT = "好友人数超过上限";
  static String USERNAME_AND_NICKNAME_CANNOT_BE_THE_SAME = "账号与昵称不能相同";
  static String PARAMETER_MISSING = "参数有缺";
  static String COIN_BALANCE_NOT_ENOUGH = "金币余额不足";
  static String YOU_DONT_KNOW_YET = "你还不认识他";
  static String POINTS_NOT_ENOUGH = "馀额或者点数不足";
  static String EXCEED_WITHDRAW_COUNT_LIMIT = "今日可提现次数已超过";
  static String EXCEED_WITHDRAW_AMOUNT_LIMIT = "今日可提现金额已超过";
  static String ILLEGAL_WITHDRAW_AMOUNT = "提现金额与后台配置不相符";
  static String THIRDPARTY_FAILED = "三方厂商回应失败";
  static String ONE_CLICK_LOGIN_ERROR = "一键登入错误";
  static String INVITATION_CODE_ERROR = "邀请码错误";
  static String DUPLICATE_PHONE_NUMBER = "电话重複";
  static String AVATAR_UNDER_REVIEW = "头像审核中";
  static String REAL_PERSON_VERIFICATION_UNDER_REVIEW = "真人认证审核中";
  static String ALBUM_UNDER_REVIEW = "相簿审核中";
  static String GREETING_UNDER_REVIEW = "招呼语审核中";
  static String NICKNAME_UNDER_REVIEW = "暱称审核中";
  static String FILE_UPLOAD_EXCEEDS_LIMIT = "档案上传超过上限";
  static String ACCOUNT_CANCELLATION_ERROR = "注销资料错误";
  static String TID_ERROR_OR_EXPIRED = "tId错误或过期(须将用户导回登入页)";
  static String SMS_LOGIN_ERROR = "简讯登入错误";
  static String REGISTER_REQUEST_TIMEOUT = "註册超时";
  static String DUPLICATE_CALL_CHARGE = "通话重複扣款";
  static String CALL_NOT_CHARGED = "通话没有扣款";
  static String CALL_REQUEST_TIMEOUT = "通话请求超时";
  static String INVALID_GENDER = "性别错误";
  static String GREETING_TEMPLATE_LIMIT_EXCEEDED = "招呼模板超过上限";
  static String GREETING_TEMPLATE_IN_USE = "招呼模板使用中";
  static String GREETING_TEMPLATE_UNDER_REVIEW = "招呼模板审核中";
  static String GREETING_TEMPLATE_UNAVAILABLE = "招呼模板不可使用";
  static String REAL_NAME_AUTH_ALREADY_CERTIFIED = "不允许重复认证(已认证过)";
  static String REAL_NAME_AUTH_FAILED = "实名认证未通过，请重新确认";
  static String REAL_NAME_AUTH_TOO_FREQUENT_10 = "您当前操作过于频繁，请1小时后尝试";
  static String REAL_NAME_AUTH_TOO_FREQUENT_3 = "您当前操作过于频繁，请5分钟后尝试";
  static String REAL_NAME_AUTH_FUNCTION_LOCK_10 = "您当前操作过于频繁，请1小时后尝试";
  static String REAL_NAME_AUTH_FUNCTION_LOCK_3 = "您当前操作过于频繁，请5分钟后尝试";
  static String WITHDRAW_TOO_FREQUENT_30_MIN = '您当前操作过于频繁，请30分钟后尝试';
  static String WITHDRAW_TOO_FREQUENT_1_MIN = '您当前操作过于频繁，请1分钟后尝试';
  static String WITHDRAW_TOO_FREQUENT_5_MIN = '您当前操作过于频繁，请5分钟后尝试';
  static String WITHDRAW_TOO_FREQUENT_1_HOUR = '您当前操作过于频繁，请1小时后尝试';
  static String INVALID_IMAGE_FORMAT = "图片格式不符";
  static String PUNCH_IN_AGAIN = "已重複签到";
  static String USER_LOGGED_IN_TWICE = "使用者重複登入";
  static String USER_NOT_LOGGED_IN = "使用者尚未登入";
  static String MEMBER_BUSY = "会员忙线中";
  static String COHESION_IS_NOT_ENOUGH = "亲密等级不足";
  static String REAL_NAME_UNDER_REVIEW = "实名验证审核中";
  static String REAL_NAME_AND_ID_CARD_IS_ALREADY_USED = "实名验证与身份资料已经被使用";
  static String WITHDRAW_IS_DIFFERENT_WITH_BACKSTAGE = "提现金额与后台配置不相符";
  static String THIRD_PART_RESPONSE_ERROR = "三方厂商回应失败";
  static String USER_NOT_AUTH_REAL_PERSON = '使用者尚未通过真人认证';
  static String MEMBER_STATE_DELETE = "账号状态注销";
  static String MEMBER_STATE_LOCK = "账号状态封号";
  static String AVATAR_REVIEW_ERROR = "头像审核未通过";
  static String CONTENT_VIOLATES_REGULATIONS = "内容违反规定";
  static String INTIMACY_POINTS_UP = "亲密度升级";
  static String GENERATE_APPLE_ORDER_ERROR = "产生苹果订单资讯失败";
  static String CAN_NOT_FOUND_DATA = "查无资料";
  static String ALREADY_ADD_LIKE = "已按过赞";
  static String CALL_IS_BLACK_LISTED = "通话已被黑名单";
  static String DATE_RANGE_NOT_EXCEED_62DAYS = "日期區間不可超過62天";
  static String SEARCH_RANGE_NOT_EXCEED_31DAYS = "查詢區間不可超過31天";
  static String NUMBER_IS_AT_RISK = "此号码存在风险，无法注册";
  static String CALL_HAS_ENDED = "通話已結束";
  static String ACTIVITY_DONATE_GENDER_ERROR = "打賞動態性別錯誤";
  static String ACTIVITY_DONATE_NOT_ENOUGH_ERROR = "打赏动态金额不足";



  static String CODE_SUCCESS = "000";
  static String CODE_PARAMETER_FORMAT_ERROR = "001";
  static String CODE_SYSTEM_MAINTENANCE = "002";
  static String CODE_USER_ACCOUNT_SUSPENDED = "003";
  static String CODE_ACCOUNT_NOT_FOUND = "004";
  static String CODE_ALREADY_A_GROUP_MEMBER = "005";
  static String CODE_GROUP_MEMBERSHIP_EXCEEDS_LIMIT = "006";
  static String CODE_INCORRECT_USERNAME_OR_PASSWORD = "007";
  static String CODE_PASSWORD_VALIDATION_ERROR = "008";
  static String CODE_PLEASE_ENTER_SIX_TO_TWELVE_DIGIT_ALPHA_NUMERIC = "009";
  static String CODE_NOT_FULLY_EXITED_ROOM = "010";
  static String CODE_PLEASE_ENTER_10_DIGITS = "011";
  static String CODE_VERIFICATION_CODE_ERROR = "012";
  static String CODE_CLICK_DURATION_TOO_SHORT = "013";
  static String CODE_NICKNAME_CONTAINS_ILLEGAL_WORDS = "014";
  static String CODE_LENGTH_LIMIT_15_CHARACTERS = "015";
  static String CODE_GROUP_NAME_ALREADY_EXISTS_1 = "016";
  static String CODE_THIS_ACCOUNT_ALREADY_EXISTS = "017";
  static String CODE_NICKNAME_CONTAINS_INAPPROPRIATE_WORDS = "018";
  static String CODE_GROUP_NOT_FOUND = "019";
  static String CODE_GROUP_NAME_ALREADY_EXISTS_2 = "020";
  static String CODE_NICKNAME_ALREADY_EXISTS = "021";
  static String CODE_NOT_A_ROOM_USER = "022";
  static String CODE_PLEASE_CHECK_AT_LEAST_ONE_PERMISSION = "024";
  static String CODE_GROUP_CONTAINS_ACCOUNTS_CANNOT_DELETE = "025";
  static String CODE_INSUFFICIENT_PERMISSIONS = "027";
  static String CODE_STATION_ERROR = "028";
  static String CODE_ALL_GROUP_MUTE = "029";
  static String CODE_GROUP_MUTE = "030";
  static String CODE_FRIEND_LIST_EXCEEDS_LIMIT = "031";
  static String CODE_USERNAME_AND_NICKNAME_CANNOT_BE_THE_SAME = "032";
  static String CODE_COIN_BALANCE_NOT_ENOUGH = "033";
  static String CODE_YOU_DONT_KNOW_YET = "034";
  static String CODE_POINTS_NOT_ENOUGH = "035";
  static String CODE_EXCEED_WITHDRAW_COUNT_LIMIT = "038";
  static String CODE_EXCEED_WITHDRAW_AMOUNT_LIMIT = "039";
  static String CODE_ILLEGAL_WITHDRAW_AMOUNT = "041";
  static String CODE_THIRDPARTY_FAILED = "042";
  static String CODE_PARAMETER_MISSING = "100";
  static String CODE_ONE_CLICK_LOGIN_ERROR = "101";
  static String CODE_INVITATION_CODE_ERROR = "102";
  static String CODE_DUPLICATE_PHONE_NUMBER = "103";
  static String CODE_AVATAR_UNDER_REVIEW = "104";
  static String CODE_REAL_PERSON_VERIFICATION_UNDER_REVIEW = "105";
  static String CODE_ALBUM_UNDER_REVIEW = "106";
  static String CODE_GREETING_UNDER_REVIEW = "107";
  static String CODE_NICKNAME_UNDER_REVIEW = "108";
  static String CODE_FILE_UPLOAD_EXCEEDS_LIMIT = "109";
  static String CODE_ACCOUNT_CANCELLATION_ERROR = "110";
  static String CODE_TID_ERROR_OR_EXPIRED = "111";
  static String CODE_SMS_LOGIN_ERROR = "117";
  static String CODE_REGISTER_REQUEST_TIMEOUT = "118";
  static String CODE_DUPLICATE_CALL_CHARGE = "120";
  static String CODE_CALL_NOT_CHARGED = "121";
  static String CODE_CALL_REQUEST_TIMEOUT = "122";
  static String CODE_CAN_NOT_FOUND_DATA = "123";
  static String CODE_INVALID_GENDER = "124";
  static String CODE_GREETING_TEMPLATE_LIMIT_EXCEEDED = "125";
  static String CODE_GREETING_TEMPLATE_IN_USE = "126";
  static String CODE_GREETING_TEMPLATE_UNDER_REVIEW = "127";
  static String CODE_GREETING_TEMPLATE_UNAVAILABLE = "128";
  static String CODE_REAL_NAME_AND_ID_CARD_IS_ALREADY_USED = "132";
  static String CODE_REAL_NAME_AUTH_FAILED = "133";
  static String CODE_REAL_NAME_AUTH_TOO_FREQUENT_10 = "135";
  static String CODE_REAL_NAME_AUTH_TOO_FREQUENT_3 = "136";
  static String CODE_REAL_NAME_AUTH_FUNCTION_LOCK_10 = "137";
  static String CODE_REAL_NAME_AUTH_FUNCTION_LOCK_3 = "138";
  static String CODE_WITHDRAW_TOO_FREQUENT_30_MIN = "139";
  static String CODE_WITHDRAW_TOO_FREQUENT_1_MIN = "140";
  static String CODE_WITHDRAW_TOO_FREQUENT_5_MIN = "141";
  static String CODE_WITHDRAW_TOO_FREQUENT_1_HOUR = "142";
  static String CODE_USER_NOT_AUTH_REAL_PERSON = "147";
  static String CODE_MEMBER_STATE_DELETE = "148";
  static String CODE_MEMBER_STATE_LOCK = "149";
  static String CODE_AVATAR_REVIEW_ERROR = "152";
  static String CODE_CALL_CHANNEL_ERROR = "153";
  static String CODE_INVALID_IMAGE_FORMAT = "200";
  static String CODE_PUNCH_IN_AGAIN = "202";
  static String CODE_ALREADY_ADD_LIKE = "204";
  static String CODE_USER_LOGGED_IN_TWICE = "998";
  static String CODE_USER_NOT_LOGGED_IN = "999";
  static String CODE_MEMBER_BUSY = "113";
  static String CODE_COHESION_IS_NOT_ENOUGH = "040";
  static String CODE_REAL_NAME_UNDER_REVIEW = "131";
  static String CODE_WITHDRAW_IS_DIFFERENT_WITH_BACKSTAGE = "041";
  static String CODE_THIRD_PART_RESPONSE_ERROR = "042";
  static String CODE_CONTENT_VIOLATES_REGULATIONS = "155";
  static String CODE_INTIMACY_POINTS_UP = "159";
  static String CODE_GENERATE_APPLE_ORDER_ERROR = "163";
  static String CODE_CALL_IS_BLACK_LISTED_ERROR = "162";
  static String CODE_DATE_RANGE_NOT_EXCEED_62DAYS = "160";
  static String CODE_SEARCH_RANGE_NOT_EXCEED_31DAYS = "161";
  static String CODE_NUMBER_IS_AT_RISK = "997";
  static String CODE_CALL_HAS_ENDED = "145";
  static String CODE_ACTIVITY_DONATE_GENDER_ERROR = "208";
  static String CODE_ACTIVITY_DONATE_NOT_ENOUGH_ERROR = "209";

  static String Network_Error = "Something went wrong";
}
